info:
  component: zuul-service

spring:
  application:
    name: zuul-service
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  sensitiveHeaders:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    user-api:
      path: /api/user/**
      serviceId: stationerycontrol-user-api
      stripPrefix: false
    certificate-api:
      path: /api/certificate/**
      serviceId: stationerycontrol-certificate-api
      stripPrefix: false
    delivery-api:
      path: /api/delivery/**
      serviceId: stationerycontrol-delivery-api
      stripPrefix: false
    township-api:
      path: /api/township/**
      serviceId: stationerycontrol-institution-api
      stripPrefix: false
    institution-api:
      path: /api/institution/**
      serviceId: stationerycontrol-institution-api
      stripPrefix: false

ribbon:
  ReadTimeout: 12000

jwt:
  secret: secret
  expiration: 7200000
